site_name: RadiantOne Cloud Native Lab

# Copyright
copyright: Copyright &copy; 2022 Radiant Logic, Inc.

# Theme
theme:
  name: material
  #logo: r1small.jpg
  nav_style: light
  navigation_depth: 5
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest    

nav:
- Home: index.md
- Prerequisites:
  - Setup: prereqs.md
  - minikube: minikube.md
- Docker: docker.md
- Docker Compose: docker-compose.md
- Kubernetes: kubernetes.md
- Helm: helm.md
- Advanced:
  - Custom Images: custom-docker.md
  - CFS: cfs.md
- Troubleshooting: troubleshooting.md
- Cheat Sheet:
  - Docker: docker-cheatsheet.md
  - Kubernetes: k8s-cheatsheet.md
